version: '3'

services:
  app:
    image: maciej197/commentapi:1.0
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: maciej
      POSTGRES_DB: commentdb
      POSTGRES_USER: admin